version: '3.7'

services:
  doumdattgi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  doumdattgi:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'doumdattgi'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306

  doumdattgi-redis:
    image: redis:latest
    ports:
      - 6379:6379
